image: kopaxgroup/node10-jdk8-flyway4-sonarscanner2-docker17-debian

before_script:
  - npx @yeutech-lab/rollup-umd-ci-before-script

stages:
  - build
  - test
  - release
  - deploy

# Job: Build
build:
  stage: build
  script:
    - npx @yeutech/rollup-umd-ci-build
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - node_modules/
  artifacts:
    when: on_success
    name: "${CI_PROJECT_PATH}-${CI_PIPELINE_ID}-${CI_COMMIT_REF_NAME}"
    untracked: true
    expire_in: 1 hour
    paths:
      - .
  only:
    - tags
    - dev
    - master
  tags:
    - docker

# Job: Test
test:
  stage: test
  coverage: '/All files[^|]*\|\s*[\d.]*\s*\|\s*[\d.]*\s*\|\s*[\d.]*\s*\|\s*([\d.]*)\s*\|\s*/'
  script:
    - npx @yeutech/rollup-umd-ci-test
  dependencies:
    - build
  only:
    - tags
    - dev
    - master
  tags:
    - docker

# Job: Release
release:
  stage: release
  script:
    - npx @yeutech/rollup-umd-ci-release
  dependencies:
    - build
  only:
    - master
  tags:
    - docker

# Pages
pages:
  stage: deploy
  script:
    - npx @yeutech/rollup-umd-ci-deploy
  artifacts:
    paths:
    - public
  only:
    - tags
  tags:
    - docker
